export const CREATE_ROOM = "CREATE_ROOM";
export const ROOM_WAS_CREATED = "ROOM_WAS_CREATED";

export const JOIN_ROOM = "JOIN_ROOM";
export const JOINED_ROOM = "JOINED_ROOM";
export const ROOM_NOT_FOUND = "ROOM_NOT_FOUND";
export const LEAVE_ROOM = "LEAVE_ROOM";
export const LEFT_ROOM = "LEFT_ROOM";

export const USER_CONNECTED = "USER_CONNECTED";
export const USER_LEFT = "USER_LEFT";
export const USER_DISCONNECTED = "USER_DISCONNECTED";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const MESSAGE_WAS_SENT = "MESSAGE_WAS_SENT";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";

export const KICK_USER = "KICK_USER";
export const YOU_ARE_KICKED = "YOU_ARE_KICKED";
export const USER_IS_KICKED = "USER_IS_KICKED";
export const YOU_ARE_DELETED = "YOU_ARE_DELETED";
export const USER_IS_DELETED = "USER_IS_DELETED";
export const YOU_ARE_NOT_DELETED = "YOU_ARE_NOT_DELETED";
export const USER_IS_NOT_DELETED = "USER_IS_NOT_DELETED";
export const KICKING_VOTE = "KICKING_VOTE";
