export const CREATE_ROOM = "CREATE_ROOM";
export const ROOM_WAS_CREATED = "ROOM_WAS_CREATED";

export const JOIN_ROOM = "JOIN_ROOM";
export const JOINED_ROOM = "JOINED_ROOM";
export const ROOM_NOT_FOUND = "ROOM_NOT_FOUND";
export const LEAVE_ROOM = "LEAVE_ROOM";
export const LEFT_ROOM = "LEFT_ROOM";

export const KICKED_FROM_ROOM = "KICKED_FROM_ROOM";
export const DELETED_FROM_ROOM = "DELETED_FROM_ROOM";
export const USER_KICKED = "USER_KICKED";
export const USER_DELETED = "USER_DELETED";

export const USER_CONNECTED = "USER_CONNECTED";
export const USER_LEFT = "USER_LEFT";
export const USER_DISCONNECTED = "USER_DISCONNECTED";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const MESSAGE_WAS_SENDED = "MESSAGE_WAS_SENDED";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
