export const SET_USERS = 'SET_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_ROOM_ID = 'SET_ROOM_ID';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const SET_GAME_TITLE = 'SET_GAME_TITLE';

export const SET_ALL_GAME_SETTINGS = 'SET_ALL_GAME_SETTINGS';

export const SET_MESSAGES = 'SET_MESSAGES';
export const MESSAGE_ON_REQUEST = 'MESSAGE_ON_REQUEST';
export const MESSAGE_ON_RESPONCE = 'MESSAGE_ON_RESPONCE';
export const MESSAGE_ON_RESPONCE_FAIL = 'MESSAGE_ON_RESPONCE_FAIL';

export const SEND_REQUEST = 'SEND_REQUEST';
export const SET_ERROR = 'SET_ERROR';

export const SEND_GAME_REQUEST = 'SEND_REQUEST';
export const SET_GAME_ERROR = 'SET_ERROR';

export const SET_ISSUES = 'SET_ISSUES';
export const ADD_ISSUE = 'ADD_ISSUE';
export const UPDATE_ISSUE = 'UPDATE_ISSUE';
export const DELETE_ISSUE = 'DELETE_ISSUE';

export const START_ROUND = 'START_ROUND';

export const SET_COMMON_NOTIFICATION = 'SET_COMMON_NOTIFICATION';
export const REMOVE_COMMON_NOTIFICATION = 'REMOVE_COMMON_NOTIFICATION';
export const SET_IMPORTANT_NOTIFICATION = 'SET_IMPORTANT_NOTIFICATION';
export const REMOVE_IMPORTANT_NOTIFICATION = 'REMOVE_IMPORTANT_NOTIFICATION';
export const SET_VOTING_NOTIFICATION = 'SET_VOTING_NOTIFICATION';

export const SET_USER_VOTE = 'SET_USER_VOTE';
export const SET_STATISTICS = 'SET_STATISTICS';
export const SET_FINAL_VOTE = 'SET_FINAL_VOTE';
