export const SET_USERS = 'SET_USERS';
export const SET_USER = 'SET_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_ROOM_ID = 'SET_ROOM_ID';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';

export const SET_ALL_GAME_SETTINGS = 'SET_ALL_GAME_SETTINGS';

export const SET_MESSAGES = 'SET_MESSAGES';
export const MESSAGE_ON_REQUEST = 'MESSAGE_ON_REQUEST';
export const MESSAGE_ON_RESPONCE = 'MESSAGE_ON_RESPONCE';
export const MESSAGE_ON_RESPONCE_FAIL = 'MESSAGE_ON_RESPONCE_FAIL';

export const SEND_REQUEST = 'SEND_REQUEST';
export const SET_ERROR = 'SET_ERROR';

export const SET_ISSUES = 'SET_ISSUES';
export const ADD_ISSUE = 'ADD_ISSUE';
export const UPDATE_ISSUE = 'UPDATE_ISSUE';
export const DELETE_ISSUE = 'DELETE_ISSUE';
